data <- read.csv("household_power_consumption.txt", sep=";", colClasses = "character")
data2 <- data[data$Date %in% c("1/2/2007", "2/2/2007"),]
png(file="plot3.png",width=480, height=480)
datetime <- strptime(paste(data2$Date, data2$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
sub1 <- as.numeric(data2$Sub_metering_1)
sub2 <- as.numeric(data2$Sub_metering_2)
sub3 <- as.numeric(data2$Sub_metering_3)
plot(x=datetime, y=sub1, type="l", xlab="", ylab="Energy sub metering")
points(x=datetime, y=sub2, type="l", col="red")
lines(x=datetime, y=sub3, type="l", col="blue")
legend("topright", lty=c(1,1), col=c("black", "red", "blue"), c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()